name: JuicyPixels-webp
version: 0.1.0.0
synopsis: WebP image support for JuicyPixels
description: Encode and decode WebP images using the JuicyPixels image types, implemented in pure Haskell.
license: BSD-3-Clause
github: ilyakooo0/JuicyPixels-webp

dependencies:
  - base >= 4.7 && < 5
  - JuicyPixels
  - bytestring
  - vector
  - primitive
  - binary

library:
  source-dirs: src

tests:
  JuicyPixels-webp-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - JuicyPixels-webp
      - hspec
      - QuickCheck
      - directory
      - filepath
